# Generated by Django 6.0 on 2025-12-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.EmailField(blank=True, max_length=255, null=True)),
                ('assunto', models.CharField(blank=True, max_length=500, null=True)),
                ('corpo_email', models.TextField(blank=True, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_anexos', models.IntegerField(default=0)),
                ('caminho_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('status_processamento', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlanilhaEnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('idg', models.IntegerField(verbose_name='IDG')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=255, verbose_name='Município')),
                ('tipo_logradouro', models.CharField(max_length=100, verbose_name='Tipo logradouro')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('tipo_lampada_anterior', models.CharField(max_length=100, verbose_name='Tipo Lâmpada Anterior')),
                ('potencia_anterior', models.CharField(max_length=50, verbose_name='Potência Anterior')),
                ('tempo_lampada_ligada_anterior', models.CharField(max_length=50, verbose_name='Tempo lâmpada ligada Anterior')),
                ('tipo_lampada_atual', models.CharField(max_length=100, verbose_name='Tipo Lâmpada Atual')),
                ('potencia_atual', models.CharField(max_length=50, verbose_name='Potência Atual')),
                ('tempo_lampada_ligada_atual', models.CharField(max_length=50, verbose_name='Tempo lâmpada ligada Atual')),
                ('data_modificacao', models.DateField(verbose_name='Data Modificação')),
                ('tipo_intervencao', models.CharField(max_length=100, verbose_name='Manutenção/Implantação/Eficiência')),
                ('tipo_medicao', models.CharField(max_length=100, verbose_name='Tipo de medição')),
                ('numero_uc', models.BigIntegerField(verbose_name='Número do UC')),
                ('tipo_circuito', models.CharField(max_length=100, verbose_name='Tipo de Circuito')),
                ('reator_situacao_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('reator_situacao_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('potencia_w', models.CharField(blank=True, max_length=50, null=True)),
                ('perda_reator_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('perda_reator_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_rede', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_plaqueta', models.BigIntegerField(blank=True, null=True)),
                ('codigo_poste', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_origem', models.CharField(blank=True, max_length=255, null=True)),
                ('acao', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_geo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('oficio_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='automacao.oficioenel')),
            ],
        ),
    ]
