# Generated by Django 6.0 on 2026-01-01 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioenel',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo Limite'),
        ),
        migrations.AddField(
            model_name='oficioenel',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
