# Generated by Django 6.0 on 2026-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0002_oficioenel_prazo_oficioenel_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficioenel',
            name='status_processamento',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Concluído')], default=0),
        ),
    ]
