# Generated by Django 6.0 on 2026-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0003_alter_oficioenel_status_processamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioenel',
            name='orgao_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
