# Generated by Django 5.0.14 on 2026-01-22 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0004_oficioenel_orgao_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_arquivos', to='automacao.oficioenel')),
            ],
        ),
    ]
