# Generated by Django 5.0.14 on 2026-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0005_anexooficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioenel',
            name='agrupamento_enel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
