# Generated by Django 5.0.14 on 2026-01-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0006_oficioenel_agrupamento_enel'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioenel',
            name='coordenadas_detectadas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
