# Generated by Django 5.0.14 on 2026-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0007_oficioenel_coordenadas_detectadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioenel',
            name='analise_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Análise Detalhada da IA'),
        ),
    ]
